### ISSUE TITLE
10.13 High Sierra

### ISSUE THREAD

**Issue by bluehomewu** [huyparody/macOS-Asus-X202E#1]
Does this work on 10.13 High Sierra?
and can u send EFI too?
Thanks for helping.

**Comment by huyparody** [comment]
> Does this work on 10.13 High Sierra?
> and can u send EFI too?
> Thanks for helping.

sorry i dont support this anymore

**Comment by bluehomewu** [comment]
> > Does this work on 10.13 High Sierra?
> > and can u send EFI too?
> > Thanks for helping.
> 
> sorry i dont support this anymore

Okay😅😅
